# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
# np.show_config()

2.2.3


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [4]:
v = np.random.random(100)
print(f"Size in bytes of v = {v.nbytes}")
# or
print(f"Size in bytes of v = {v.size * v.itemsize}")

Size in bytes of v = 800
Size in bytes of v = 800


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
!python3 -c "import numpy; numpy.info(numpy.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
v = np.random.random(5)
print(v)
print(f"Reverse v = {v[::-1]}")

[0.19141626 0.67040787 0.73677947 0.52932612 0.92385167]
Reverse v = [0.92385167 0.52932612 0.73677947 0.67040787 0.19141626]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
mat = np.arange(9).reshape(3, 3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
v = np.array([1, 2, 0, 0, 4, 0])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
mat = np.eye(3)
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
arr = np.random.random((3, 3, 3))
print(arr)

[[[0.50743332 0.94586722 0.61138968]
  [0.31503523 0.04527109 0.53624599]
  [0.2721911  0.82631866 0.49473506]]

 [[0.41546358 0.63037352 0.56811394]
  [0.10543205 0.00294178 0.04258314]
  [0.54349896 0.78424203 0.94273808]]

 [[0.77398013 0.57525926 0.23753832]
  [0.07005115 0.58483673 0.60522308]
  [0.43352955 0.02394891 0.68982507]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
arr = np.random.randint(0, 100, (5, 5))
print(f"Min & Max values of matrix \n{arr} = [{arr.min()}, {arr.max()}]")

Min & Max values of matrix 
[[ 3 79 60 38 53]
 [76 24 29 31 20]
 [ 5 17 56  3  9]
 [30 13  4 63  2]
 [58 56 76  8 84]] = [2, 84]


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
v = np.random.random(30)
print(f"The mean value of v = {v.mean()}")

The mean value of v = 0.47169505181923344


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
arr = np.ones((10, 10))
arr[1:-1, 1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
arr = np.random.random((5, 5))
arr[:, [0, -1]] = 0
arr[[0, -1], :] = 0
print(arr)

# or

arr = np.pad(arr, pad_width=1, mode="constant", constant_values=0)

[[0.         0.         0.         0.         0.        ]
 [0.         0.89522892 0.91828637 0.28525971 0.        ]
 [0.         0.43349777 0.65529382 0.67109113 0.        ]
 [0.         0.62800225 0.88972439 0.82823257 0.        ]
 [0.         0.         0.         0.         0.        ]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
mat = np.eye(5, k=-1, dtype="int") * np.array([1, 2, 3, 4, 0])
print(mat)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
mat = np.full((8, 8), "⚫️", dtype="str")
mat[1::2, ::2] = "⚪️"
mat[::2, 1::2] = "⚪️"
print(mat)

[['⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪']
 ['⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫']
 ['⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪']
 ['⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫']
 ['⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪']
 ['⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫']
 ['⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪']
 ['⚪' '⚫' '⚪' '⚫' '⚪' '⚫' '⚪' '⚫']]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [20]:
print(
    f"The 100th index element of a (6, 7, 8) shape array = {np.unravel_index(99,(6,7,8))}"
)

The 100th index element of a (6, 7, 8) shape array = (np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
row = np.array([["🖤", "🤍"], ["🤍", "🖤"]])
print(np.tile(row, (4, 4)))

[['🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍']
 ['🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤']
 ['🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍']
 ['🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤']
 ['🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍']
 ['🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤']
 ['🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍']
 ['🤍' '🖤' '🤍' '🖤' '🤍' '🖤' '🤍' '🖤']]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
mat = np.random.random((5, 5))
norm = (mat - mat.min()) / (mat.max() - mat.min())
print(norm)

[[5.92452613e-01 0.00000000e+00 1.00000000e+00 6.32720309e-02
  3.91580092e-02]
 [9.73772597e-01 7.77842539e-01 5.17129946e-01 1.54429682e-01
  4.28187488e-01]
 [8.31196332e-01 2.00406162e-01 3.82391805e-01 8.24772186e-01
  8.56607910e-01]
 [7.00593346e-01 2.35077801e-02 7.10070822e-01 8.05066287e-01
  8.10944322e-01]
 [5.57786241e-01 9.13913874e-05 2.32826656e-01 3.97068218e-01
  5.73461877e-01]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte), ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
mat_A = np.random.random((5, 3))
mat_B = np.random.random((3, 2))

print(np.matmul(mat_A, mat_B))

[[0.48773141 0.68617098]
 [0.30191971 0.39846574]
 [0.72155948 0.43468583]
 [0.70352223 0.37242921]
 [0.71887218 0.77383426]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
arr = np.arange(10)
arr[(3 < arr) & (arr < 8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
# 9 sum(iterable, start)
# 10 numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
v = np.arange(5)
print(v**v)
print(2 << v >> 2)
print(v < -v)
print(1j * v)
print(v / 1 / 1)
# this one ---> print(v < v > v)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [28]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


/var/folders/rj/6cfjbftj3tgcdt_v_3n95t_r0000gn/T/ipykernel_28453/3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
/var/folders/rj/6cfjbftj3tgcdt_v_3n95t_r0000gn/T/ipykernel_28453/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
/var/folders/rj/6cfjbftj3tgcdt_v_3n95t_r0000gn/T/ipykernel_28453/3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
arr = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

# More readable but less efficient
print(np.where(arr > 0, np.ceil(arr), np.floor(arr)))

[ 4. -8.  8.  4.  7. -6. -3.  9. -7.  7.]
[ 4. -8.  8.  4.  7. -6. -3.  9. -7.  7.]


#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
arr_a = np.random.randint(0, 10, 10)
arr_b = np.random.randint(0, 10, 10)
print(np.intersect1d(arr_a, arr_b))

[0 1 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
# defaults = np.seterr(all="ignore")
# Z = np.ones(1) / 0

# Back to sanity
# _ = np.seterr(**defaults)

# Equivalently with a context manager
# with np.errstate(all="ignore"):
#     np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [2]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/var/folders/rj/6cfjbftj3tgcdt_v_3n95t_r0000gn/T/ipykernel_53366/2770867030.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [5]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, today)

2025-03-08 2025-03-09 2025-03-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
dates = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [13]:
A = np.arange(3, dtype='float')
B = np.arange(5,8, dtype='float')
print(A, B)
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[0. 1. 2.] [5. 6. 7.]
[-0.  -3.5 -9. ]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
arr = np.random.random(5) * 10

print(arr)
print(arr // 1) # 1
print(np.floor(arr)) # 2
print(arr - arr%1) # 3
print(np.trunc(arr)) # 4
print(arr.astype(int)) # 5


[4.20421957 0.51900086 8.75012931 3.94679786 5.86261876]
[4. 0. 8. 3. 5.]
[4. 0. 8. 3. 5.]
[4. 0. 8. 3. 5.]
[4. 0. 8. 3. 5.]
[4 0 8 3 5]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [65]:
mat = np.tile(np.arange(5), (5, 1))
print(mat)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [70]:
def generator():
    for i in range(10):
        yield i
arr = np.fromiter(generator(), dtype='float', count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [79]:
v = np.random.random(10)
print(v)

# or

v1 = np.linspace(0,1,11,endpoint=False)[1:]
print(v1)

[0.22977096 0.83591239 0.70353688 0.39898746 0.84698468 0.28023561
 0.87291542 0.43179664 0.30584444 0.87158499]
[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [85]:
v = np.random.random(10) * 10
print(v)
v.sort()
print(f"Sorted v = {v}")

[6.74529308 1.64509425 3.54936112 0.52093748 6.70366105 5.03363688
 5.74680982 3.47580875 7.34358902 5.62314336]
Sorted v = [0.52093748 1.64509425 3.47580875 3.54936112 5.03363688 5.62314336
 5.74680982 6.70366105 6.74529308 7.34358902]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [89]:
arr = np.add.reduce(np.arange(5))
print(arr)

10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
for i in range(10000):
    A = np.random.randint(1, 10, 5)
    B = np.random.randint(1, 10, 5)

    eq = np.allclose(A, B) # np.array_equal(A, B) no tolerance
    if eq:
        print(f"{i} --> {eq}")
        print(A, B)
        print("Success")
        break

    if i + 1 == 10000:
        print("Failure")


Failure


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
arr = np.arange(10)
arr.flags.writeable = False
arr[2] = 2 # ValueError: assignment destination is read-only

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [157]:
mat = np.random.random((10, 2))
X, Y = mat[:, 0], mat[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print(f"R = {R}\nT = {T}")

R = [0.78482248 0.41317028 0.16613528 0.74391076 0.58195125 0.61423257
 0.34993648 1.26804068 1.12150952 0.82364783]
T = [1.36714817 0.57752875 1.20123494 0.50945085 1.23767532 0.50735034
 0.13130735 0.84241424 0.97902823 0.45876283]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [159]:
v = np.random.randint(20, 2000, 10)
print(v)
v[v.argmax()] = 0
print(v)

[1178 1833  860  223 1517  551  159  534 1369   61]
[1178    0  860  223 1517  551  159  534 1369   61]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)